### ISSUE TITLE
Partner Create by VAT NRC autofill

### ISSUE THREAD

**Issue by misuv** [OCA/l10n-romania#40]
Hi

the Partner Create by VAT does not auto fill the NRC for Romanian companies

I didn't try yet for foreign companies

since the Romanian law require both NRC and VAT no on invoices, this could be a problem in future

could you fix this please?

thank you

**Comment by feketemihai** [comment]
Hi @misuv , the module https://github.com/OCA/l10n-romania/tree/11.0/l10n_ro_partner_create_by_vat was rewritten on v11 to get data directly from Anaf, but Anaf webservice doesn't provide the NRC field, so will have to improve the module or create a new module to fetch data from Mfinante, but it will take some time.

**Comment by misuv** [comment]
I would be great @feketemihai 

or we can change the Romanian law :-). Other countries don't require VAT no, NRC & stamp on official documents

**Comment by feketemihai** [comment]
Updated but only in V13 and 14 with all data needed.
