### ISSUE TITLE
[V15] Probleme cu AVCO - Automated

### ISSUE THREAD

**Issue by FreezeS** [OCA/l10n-romania#461]
Salutare,

Pe runboat, oca/l10n-romania 15.0 (8acd1f86), resetat, fac urmatoarele:
- Settings/Romania: setez conturile cu cele cerute, bifez Romanian accounting
- Inventory/Configuration/Product Categories - Create
- Completez nume, la Costing method selectez AVCO, Inventory Valuation - Automated
- Cand dau click pe save, apare eroarea: 
Invalid fields:
Stock Valuation Account

Am testat si pe alt runboat, fara modulele romanesti instalate si acolo nu primesc eroarea asta.

Pe lab-ul meu, cand selectez Automated, imi apar 3 campuri noi (Price Difference Accound, Stock Valuation Account, Stock Journal) insa pe runboat-ul celalalt nu apare nimic si nici nu da eroare iar apoi functioneaza bine.
Am dat de eroarea asta cand incercam sa reproduc alta eroare (produsele AVCO nu intra pe stoc) insa e posibil sa fie legate.

**Comment by FreezeS** [comment]
Salut,

Nu vreau sa insist, dar e destul de important sa rezolv problema asta cumva inainte sa migram pe Odoo.
Vad ca inca persista si la ultimul commit.

Este o problema/limitare cunoscuta?
Cum recomandati sa facem stock valuation pe Romania?

**Comment by feketemihai** [comment]
Trebuie sa ai grupul de Accounting/Accountant ca sa poti completa contul de stock valuation.
