### ISSUE TITLE
[16] ANAF Sync Callback URL este HTTP

### ISSUE THREAD

**Issue by FreezeS** [OCA/l10n-romania#760]
Salut,

Am un server CE V16 instalat in docker si cu un reverse proxy NGINX care redirecteaza automat catre HTTPS.
Cand incerc sa iau access tokenul de la ANAF primesc eroarea:
```
{
  "error":"invalid_request",
  "error_description":"Redirect-URI (http://XXXXX.ro/l10n_ro_account_anaf_sync/anaf_oauth/2) does not match with client app configuration."
}
``` 
In interfata Odoo apare callback-ul la fel si nu e editabil:
![image](https://github.com/OCA/l10n-romania/assets/2807003/46b0fd4f-ee43-485a-b4aa-8cefea622828)

In tabela l10n_ro_account_anaf_sync nu e pe nici o coloana.
Am incercat de test sa pun callback-ul cu HTTP la anaf dar e obligatoriu HTTPS.

E vreo setare care imi scapa?

**Comment by feketemihai** [comment]
Salut, in principiu in callback url iti ia url-ul instantei de Odoo, get_base_url, asta inseamna ca ai gresit ceva in Nginx ca nu iti face redirectarea catre https.

**Comment by FreezeS** [comment]
Am mai sapat un pic si am gasit solutia. 
get_base_url citeste din Settings - Technical - System Parameters variabila "web.base.url". Acolo trebuie editat si schimbat din http in https apoi trebuie adaugat un parametru nou "web.base.url.freeze" cu valoarea "True". 
Presupun ca asta o sa fie o problema frecventa, poate ar trebui trecuta in documentatie.
