### ISSUE TITLE
If some product from invoice are not affected by cutom tax?

### ISSUE THREAD

**Issue by IRRI-GIT** [OCA/l10n-romania#782]
module: l10n_ro_dvi
version: 15.0

**Steps to reproduce**
- ...
If we have some products in DVI witch are not affected by custom tax, can we have a landed cost distribution the same as in DVI document?
https://drive.google.com/file/d/16rCdfOiHWh7s6e53GRY93xB0gpB-4lvD/view?usp=drivesdk
**Current behavior**

Landed cost trying to distibute taxes on all products from the receipt ( and not based on DVI)

**Expected behavior**

It is nice to distribute amounts to eaach product the same as it is in DVI document. Skipping the products not affected by tax.

**Comment by feketemihai** [comment]
This you can do with normal Landed Cost, you select the reception and the products that you want for distribution. It's the normal Odoo behaviour.

**Comment by IRRI-GIT** [comment]
Thank you for promt answer Mihai!
Here is more detaled video: https://drive.google.com/file/d/1mqfOU-vJX-ovIL41Eeb2QmKU5lzJX-l2/view?usp=drivesdk
Maybe you find useful that functionality for your product:
- add additional columns to the product list in DVI document  to be able to set a precise tax distribution on each product.
-  transfer to LC document correct information about each product to distribute the costs.
