### ISSUE TITLE
Usage giving account

### ISSUE THREAD

**Issue by FreezeS** [OCA/l10n-romania#839]
Salut,

In pagina de setari, pentru campul "Romania - Usage Giving Account" cere sa selectez 8035 dar acesta nu este in lista:

![image](https://github.com/OCA/l10n-romania/assets/2807003/3a4b36b7-e855-4d1d-b33b-4b67dbbf07cb)

Daca scriu "8035" imi cere sa il creez desi contul exista in Chart of accounts.

Cum e corect sa fac?

**Comment by bogdanhu** [comment]
se uita dupa tipul "Alte venituri"; cred ca trebuia filtrul pus pentru In afara bilantului

**Comment by bogdanhu** [comment]
in ./l10n_ro_config/models/res_company.py
l10n_ro_property_stock_usage_giving_account_id = fields.Many2one(
        "account.account",
        string="Romania - Usage Giving Account",
        domain="[('account_type', '=', **'income_other'**)]",
        help="This account will be used as the usage giving "
        "account in account move line.",
cred ca  trebuia sa fie off_balance

**Comment by feketemihai** [comment]
A fost scos domeniul

**Comment by FreezeS** [comment]
La mine inca se mentine problema (V16 tocmai am facut update la cod in momentul asta): 
![image](https://github.com/OCA/l10n-romania/assets/2807003/9e92a42d-edd3-48a8-927f-156833c3183c)
