### ISSUE TITLE
Valori negative e-factura

### ISSUE THREAD

**Issue by FreezeS** [OCA/l10n-romania#859]
Salutare,

Care este cea mai buna abordare pentru valorile negative in e-factura? (ex: discount)
ANAF vrea valorile produselor sa fie pozitive si cantitatea negativa insa din ce am inteles nu este "best practice" pe Odoo, unde se recomanda cantitatea pozitiva si valoarea negativa.

Cum este cel mai bine de procedat?
1. In factura qty: pozitiv, val: negativ si schimbat in XML inainte de trimitere la e-factura.
2. In factura qty: negativ, val: pozitiv. Asta e ok pentru e-factura dar afecteaza oare facturile storno?

**Comment by feketemihai** [comment]
In factura qty: negativ, val: pozitiv. Asta e ok pentru e-factura dar afecteaza oare facturile storno?

pretul nu poate fi negativ
