### ISSUE TITLE
eFactura: Factura a mai fost transmisa anterior cu index=

### ISSUE THREAD

**Issue by FreezeS** [OCA/l10n-romania#936]
Salutare,

Se pare ca la un moment dat s-a trimis aceasi factura de mai multe ori la ANAF iar "ID eFactura Transaction" salvat in baza de date este cel cu eroarea din titlu.

Este vreo posibilitate de a corecta din interfata? 
Daca nu, unde pot inlocui in baza de date id-ul cu cel bun si unde trebuie sa populez "ID eFactura"?

**Comment by adrian-dks** [comment]
Salut, 
Nu e clar, ai confirmarea din SPV ca e aceeasi factura trimisa de mai multe ori? S-a trimis dintr-o eroare operatională? 
Daca e o eroare de logica in cod, te rog sa vi cu mai multe detalii. 
Daca este o eroare operationala, nu face obiectul discutiilor aici.

**Comment by FreezeS** [comment]
Operatorul a dat click de multe ori pe butonul "Process now" si la un moment dat a aparut mesajul "The invoice was not validated by ANAF."
Cand am verificat numarul "ID eFactura Transaction" la ANAF, era eroarea din titlu.
Tinand cont ca factura e trimisa deja la ANAF, nu o pot anula si sa o trimit din nou. 
Singura solutie pe care o vad e sa identific la ANAF factura procesata, sa gasesc ID-urile si sa le trec in Odoo.
Doar ca nu asta nu e posibil din interfata deci trebuie sa scriu direct in baza de date.

As sugera cateva imbunatatiri pentru a preveni aceste probleme in viitor:

1. Butonul "Process now" sa devina inactiv la click si sa revina doar cand primeste raspuns de la ANAF (sau timeout)
2. Adaugare buton "Get ANAF error" care sa apara doar cand factura nu a fost validata de ANAF
3. In cazul in care eroarea face parte dintr-o lista (ex: factura a mai fost trimisa anterior), sa permita schimbarea manuala a "ID eFactura Transaction". In acel moment trebuie validat ID-ul sa fie unic si verificat statusul facturii la ANAF iar daca a fost procesata, trebuie preluate datele ei si actualizata baza de date.

**Comment by adrian-dks** [comment]
Poti sa faci un PR cu aceasta propunere, sa vedem implementarea.
